import type { LucideIcon } from "lucide-react";
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Clipboard,
  Clock,
  Cloud,
  CreditCard,
  Download,
  Eye,
  File,
  Folder,
  Heart,
  Home,
  Image,
  Info,
  Link2,
  Lock,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Minus,
  Pause,
  Phone,
  Play,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Share2,
  ShoppingBag,
  ShoppingCart,
  Star,
  Trash2,
  Upload,
  User,
  Volume2,
  Wifi,
  X,
} from "lucide-react";

/** Stroke weights from the Icons + Logo sheet */
export const iconWeights = {
  thin: 1,
  regular: 1.5,
  bold: 2.5,
} as const;

export type IconWeight = keyof typeof iconWeights;

export const iconSizes = {
  xs: 16,
  sm: 20,
  md: 24,
  lg: 32,
  xl: 40,
} as const;

export type IconSize = keyof typeof iconSizes;

/** Core UI icon registry (Lucide mapping) */
export const iconRegistry = {
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  menu: Menu,
  close: X,
  check: Check,
  plus: Plus,
  minus: Minus,
  search: Search,
  settings: Settings,
  home: Home,
  user: User,
  mail: Mail,
  message: MessageCircle,
  phone: Phone,
  bell: Bell,
  calendar: Calendar,
  clock: Clock,
  star: Star,
  heart: Heart,
  play: Play,
  pause: Pause,
  volume: Volume2,
  camera: Camera,
  image: Image,
  file: File,
  folder: Folder,
  upload: Upload,
  download: Download,
  cloud: Cloud,
  link: Link2,
  share: Share2,
  eye: Eye,
  lock: Lock,
  mapPin: MapPin,
  info: Info,
  refresh: RefreshCw,
  trash: Trash2,
  cart: ShoppingCart,
  bag: ShoppingBag,
  card: CreditCard,
  clipboard: Clipboard,
  circle: Circle,
  wifi: Wifi,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;

/** Icons showcased on the design-system page (representative grid) */
export const iconShowcase: IconName[] = [
  "arrowUp",
  "arrowDown",
  "arrowLeft",
  "arrowRight",
  "chevronUp",
  "chevronDown",
  "menu",
  "close",
  "check",
  "plus",
  "minus",
  "search",
  "settings",
  "home",
  "user",
  "mail",
  "message",
  "phone",
  "bell",
  "calendar",
  "star",
  "heart",
  "play",
  "pause",
  "camera",
  "file",
  "folder",
  "upload",
  "download",
  "link",
  "eye",
  "lock",
  "mapPin",
  "info",
  "refresh",
  "trash",
  "cart",
  "wifi",
];

export const brandIcons = ["google", "facebook", "apple"] as const;
export type BrandIconName = (typeof brandIcons)[number];
